# Generated by Django 3.2.9 on 2021-11-09 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('order_sell', models.IntegerField()),
                ('real_selled', models.IntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(blank=True, max_length=220, null=True)),
                ('type', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('real_selled', models.IntegerField()),
                ('order_sell', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver_name', models.CharField(max_length=10)),
                ('receiver_phone', models.CharField(max_length=12)),
                ('dog_case1', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('dog_case2', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('dog_keyring', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('cat_case1', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('cat_case2', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('cat_keyring', models.IntegerField(blank=True, choices=[(None, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('sell', models.IntegerField()),
                ('shipping', models.CharField(choices=[(None, '선택'), ('0', '직접수령(    0원)'), ('1', '택배배송(3,500원)')], max_length=1)),
                ('detail_address', models.CharField(blank=True, help_text='시/도를 포함한 배송받을 주소를 상세히 입력해주세요.', max_length=100)),
                ('hufs', models.BooleanField(blank=True, default=False)),
                ('deposit_name', models.CharField(max_length=10)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('deposit_check', models.IntegerField(blank=True, null=True)),
                ('real_selled', models.IntegerField()),
                ('cashreceipts', models.IntegerField(blank=True, null=True)),
                ('shipping_state', models.CharField(blank=True, choices=[('0', '준비중'), ('1', '배송중'), ('2', '배송완료')], default='0', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
