# Generated by Django 3.2.9 on 2021-11-21 07:21

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('kapchikachi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cashreceipts_num',
            field=models.CharField(blank=True, help_text='현금영수증 요청 시 입력해주세요.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cashreceipts',
            field=models.CharField(choices=[('0', '발급안함'), ('1', '발급')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cat_case1',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cat_case2',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cat_keyring',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='"석수" 관련 멘트를 남겨주시면 후원금을 석수에게 지급합니다!'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='detail_address',
            field=markdownx.models.MarkdownxField(blank=True, help_text='택배배송 선택시 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dog_case1',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dog_case2',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dog_keyring',
            field=models.IntegerField(blank=True, choices=[(0, '선택(0개)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='shipping',
            field=models.CharField(choices=[('0', '직접수령(    0원)'), ('1', '택배배송(3,500원)')], help_text='직접수령 선택시 담당자가 연락드립니다.', max_length=1),
        ),
    ]
