# Generated by Django 3.1.3 on 2021-11-22 14:19

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('kapchikachi', '0002_auto_20211121_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cashreceipts',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cashreceipts_num',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='"석수" 관련 멘트를 남겨주시면 후원금을 석수에게 지급합니다!'),
        ),
    ]
