# Generated by Django 3.1.3 on 2021-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapchikachi', '0003_auto_20211122_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='shipping',
            field=models.CharField(choices=[('0', '직접수령(    0원)'), ('1', '택배배송(2,800원)')], help_text='직접수령 선택시 담당자가 연락드립니다.', max_length=1),
        ),
    ]
